from enum import Enum as PyEnum

class Fruit(PyEnum):
    WATER_MELON = 'WATER_MELON'
    ORIENTAL_MELON = 'ORIENTAL_MELON'
    PEACH = 'PEACH'

class FruitPart(PyEnum):
    WATER_MELON_CIRCULAR = 'WATER_MELON_CIRCULAR'
    WATER_MELON_STRIPES = 'WATER_MELON_STRIPES'
    WATER_MELON_NAVEL = 'WATER_MELON_NAVEL'
    ORIENTAL_MELON_NAVEL = 'ORIENTAL_MELON_NAVEL'
    ORIENTAL_MELON_OVAL = 'ORIENTAL_MELON_OVAL'
    ORIENTAL_MELON_INJURY = 'ORIENTAL_MELON_INJURY'
    PEACH_RED = 'PEACH_RED'
    PEACH_LINE = 'PEACH_LINE'
    PEACH_INJURY = 'PEACH_INJURY'